### ISSUE TITLE
build: problem with 'max' in abseil failure_signal_handler  

### ISSUE THREAD

**Issue by newbie-02** [ibireme/c_numconv_benchmark#4]
friendly hello @all,  
  
I did! search for old issues, none where shown???, first bug?  

**Describe the bug**
build fails with:  
``` 
/home/ubuntu/gnome.lnk/000_from_scratch/c_numconv_benchmark/vendor/abseil-cpp/absl/debugging/failure_signal_handler.cc: In function ‘bool absl::SetupAlternateStackOnce()’:
/home/ubuntu/gnome.lnk/000_from_scratch/c_numconv_benchmark/vendor/abseil-cpp/absl/debugging/failure_signal_handler.cc:138:32: error: no matching function for call to ‘max(long int, int)’
138 |   size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;
|                        ~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/algorithm:61,
from /home/ubuntu/gnome.lnk/000_from_scratch/c_numconv_benchmark/vendor/abseil-cpp/absl/debugging/failure_signal_handler.cc:35:
/usr/include/c++/11/bits/stl_algobase.h:254:5: note: candidate: ‘template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)’
254 |     max(const _Tp& __a, const _Tp& __b)  
```
  
**Your environment**
 - OS: Ubuntu 22.04.2 LTS  
 - Compiler g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0       ( gcc the same ),  
  
**Additional context**
after trying different type adaptions as proposed in [why-max-function-in-c-giving-error-no-matching-function-for-call-to-max-s](https://stackoverflow.com/questions/72795620/why-max-function-in-c-giving-error-no-matching-function-for-call-to-max-s)  
the build succeeds, but  
`./run_itoa -o report_itoa.html`  
is happily throwing errors like:  
```  
------[verify]---------
verify yy             
    i32 error: -2147483648 -> -00 (length 11 -> 3)
    i64 error: -9223372036854775808 -> -0 (length 20 -> 2)  
```  
  
I followed the build instructions as simply as possible,

**Comment by ibireme** [comment]
The compilation error can be resolved by upgrading `abseil-cpp` to the latest version. 
The runtime error was caused by a signed/unsigned integer conversion issue in the itoa_i32_yy() series of functions. 

Fixed here: https://github.com/ibireme/c_numconv_benchmark/commit/a9d3f96beeea88f5020273281a3bd0ef1cb673b1

**Comment by newbie-02** [comment]
:-)  works, nice, thank you :-)
