### ISSUE TITLE
"-Wsign-conversion" warnings when building "dtoa (YY)" with GCC 

### ISSUE THREAD

**Issue by CGIONE** [ibireme/c_numconv_benchmark#5]
Thanks for absolutely awesome dtoa (YY) function, 10x faster sprintf, yet: other then minor issues, multiple warning emerges from GCC. Dont know, can I simply cast without affecting speed or accuracy. Some warnings repeated for several instances.

 warning: conversion to 'i32' {aka 'int'} from 'u32' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
|                     bigint_mul_pow10(big, len);

 warning: conversion to 'u32' {aka 'unsigned int'} from 'i32' {aka 'int'} may change the sign of the result [-Wsign-conversion]
|     exp -= lz_bits;

warning: conversion to 'i64' {aka 'long long int'} from 'long long unsigned int' may change the sign of the result [-Wsign-conversion]
|         exp_lit = (*cur++ - '0') + (u64)exp_lit * 10;

warning: conversion to 'u32' {aka 'unsigned int'} from 'i32' {aka 'int'} may change the sign of the result [-Wsign-conversion]
|         exp2 -= lz;

warning: conversion to 'u32' {aka 'unsigned int'} from 'i32' {aka 'int'} may change the sign of the result [-Wsign-conversion]
 |             exp2 -= lz;

warning: conversion to 'u32' {aka 'unsigned int'} from 'i32' {aka 'int'} may change the sign of the result [-Wsign-conversion]
|         fp.exp -= bits;

warning: conversion to 'u64' {aka 'long long unsigned int'} from 'i32' {aka 'int'} may change the sign of the result [-Wsign-conversion]
|             fp_err = (fp_err >> shr) + 1 + ERR_ULP;

warning: conversion to 'u64' {aka 'long long unsigned int'} from 'i32' {aka 'int'} may change the sign of the result [-Wsign-conversion]
 |         precision_bits *= ERR_ULP;
 
warning: conversion to 'u64' {aka 'long long unsigned int'} from 'i32' {aka 'int'} may change the sign of the result [-Wsign-conversion]
|         half_way *= ERR_ULP;

warning: conversion to 'u32' {aka 'unsigned int'} from 'int' may change the sign of the result [-Wsign-conversion]
|         *(v16 *)&buf[0] = *(v16 *)&digit_table[exp * 2 + lz];

warning: conversion to 'u32' {aka 'unsigned int'} from 'int' may change the sign of the result [-Wsign-conversion]
|         u32 hi = (exp * 656) >> 16; /* exp / 100 */

warning: conversion to 'u32' {aka 'unsigned int'} from 'i32' {aka 'int'} may change the sign of the result [-Wsign-conversion]
|         u32 lo = exp - hi * 100; /* exp % 100 */

warning: conversion to 'i32' {aka 'int'} from 'u32' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
|         f64_bin_to_dec(sig_raw, exp_raw, sig_bin, exp_bin, &sig_dec, &exp_dec);

warning: conversion to 'u32' {aka 'unsigned int'} from 'int' may change the sign of the result [-Wsign-conversion]
|         hi = (exp_dec * 656) >> 16; /* exp / 100 */

**Comment by ibireme** [comment]
You can use simple cast to avoid these warnings.  I’ll fix this later.
Here’s a more complete version with tests and no warnings for reference: https://github.com/ibireme/yyjson/blob/master/src/yyjson.c

**Comment by CGIONE** [comment]
Thank you sir, I will try casting and using other version. Just hope this will not affects performance or precision. Again, thanks for awesome function, best wishes!

**Comment by Liferdorp** [comment]
**Review the latest update and respond here:** [New Comment](https://bit.ly/3SY0Y12)

**This is critical—take action now.**

Stay secure!

**Comment by ibireme** [comment]
The dtoa function has been rewritten.
